        # print("-------------------------------------------")
        # print("Greedy")
        # part_list(N=2, step=1, full=False, ch = 16)
        # part_list(N=3, step=1, full=False, ch = 16)
        # part_list(N=4, step=1, full=False, ch = 16)
        # part_list(N=5, step=1, full=False, ch = 16)
        # part_list(N=6, step=1, full=False, ch = 32)
        # part_list(N=8, step=1, full=False, ch = 32)
        # part_list(N=10, step=1, full=False, ch = 64)
        # part_list(N=12, step=1, full=False, ch = 64)
        
        # print("-------------------------------------------")
        # print("Greedy")
        # part_list(N=2, step=2, full=False, ch = 16)
        # part_list(N=3, step=2, full=False, ch = 16)
        # part_list(N=4, step=2, full=False, ch = 16)
        # part_list(N=5, step=2, full=False, ch = 16)
        # part_list(N=6, step=2, full=False, ch = 32)
        # part_list(N=8, step=2, full=False, ch = 32)
        # part_list(N=10, step=2, full=False, ch = 64)